SELECT moz_places.id as pl_id,
    moz_places.url as pl_url,
    moz_places.title as pl_title,
    moz_places.rev_host as pl_rev_host,
    moz_places.visit_count as pl_visit_count,
    moz_places.hidden as pl_hidden,
    moz_places.typed as pl_typed,
    moz_places.frecency as pl_frecency,
    moz_places.last_visit_date as pl_last_visit_date,
    moz_places.guid as pl_guid,
    moz_places.foreign_count as pl_foreign_count,
    moz_places.url_hash as pl_url_hash,
    moz_places.description as pl_description,
    moz_places.preview_image_url as pl_preview_image_url,
    moz_places.site_name as pl_site_name,
    moz_places.origin_id as pl_origin_id,
    moz_places.recalc_frecency as pl_recalc_frecency,
    moz_places.alt_frecency as pl_alt_frecency,
    moz_places.recalc_alt_frecency as pl_recalc_alt_frecency,
    moz_historyvisits.'from_visit' as 'his_from_visit',
    moz_historyvisits.'place_id' as 'his_place_id',
    moz_historyvisits.'visit_date' as 'his_visit_date',
    moz_historyvisits.'visit_type' as 'his_visit_type',
    moz_historyvisits.'session' as 'his_session',
    moz_historyvisits.'source' as 'his_source',
    moz_historyvisits.'triggeringPlaceId' as 'his_triggeringPlaceId'
from moz_historyvisits
join moz_places on moz_places.id = moz_historyvisits.place_id;